#pragma once
#include <algorithm>
#include <array>
#include <atomic>
#include <cassert>
#include <cstdint>
#include <map>
#include <memory>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include <windows.h>

#include <CommCtrl.h>
#include <CommonControls.h>
#include <ImageHlp.h>
#include <intsafe.h>
#include <memoryapi.h>
#include <ntstatus.h>
#include <objidl.h>
#include <shlwapi.h>
#include <strsafe.h>
#include <tlhelp32.h>
#include <uxtheme.h>
#include <vssym32.h>
#include <wincodec.h>
#include <winnt.h>
#include <winternl.h>
#include <wtypes.h>
